### ISSUE TITLE
Language file mentions that Haunted is an innocent despite it being a Traitor role

### ISSUE THREAD

**Issue by The1337Gh0st** [AaronMcKenney/ttt2-role_haunt#1]
In the language file, the role description says that it is an innocent, despite it being a Traitor role. 

This is the line that is the issue:
`L["ttt2_desc_" .. HAUNTED.name] = [[The Haunted is an innocent who revives after their killer dies!]]`

This should be changed to:
`L["ttt2_desc_" .. HAUNTED.name] = [[The Haunted is a traitor who revives after their killer dies!]]`

**Comment by AaronMcKenney** [comment]
Fixed. Thanks for taking the time to find this and create a GitHub issue!
